name: Backend and iOS Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: macos-latest
    
    steps:
      - uses: ikalnytskyi/action-setup-postgres@v4
        with:
          username: friends_db_user
          password: SzhaUgWdzjlrVOpScJCGZrfNsUvhVv2d
          database: friends_db
          port: 5432
        id: postgres
    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start Backend
        run: |
          cd network_app/backend
          npm install
          npm run migrate 
          npm start &

     # - name: Build iOS App
     #   run: |
    #      cd network_app/Friends
   #        xcodebuild -project Friends.xcodeproj -scheme Friends build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Run Xcode Tests
        run: |
          cd network_app/Friends
           xcodebuild test -scheme Friends -project Friends.xcodeproj -destination 'platform=iOS Simulator, name=iPhone 15, OS=17.0' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
