name: Backend and iOS Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: macos-latest
    
    steps:
      - uses: ikalnytskyi/action-setup-postgres@v4
        with:
          username: ${{ secrets.DB_USER }}
          password: ${{ secrets.DB_PASSWORD }}
          database: friends_db
          port: 34837
        id: postgres
    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start Backend
        run: |
          cd backend
          npm install
          # npm migrate + insert test data
          npm start &

      - name: Build iOS App
        run: |
          cd Frontend
           xcodebuild -project frontend.xcodeproj -scheme frontend build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Run Xcode Tests
        run: |
          cd Frontend
          # doesnt work
           xcodebuild -project frontend.xcodeproj -scheme frontend test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
